apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-recipes-celery
  labels:
    app: my-recipes-celery
    group: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-recipes-celery
  template:
    metadata:
      labels:
        app: my-recipes-celery
        group: db
    spec:
      containers:
        - name: my-recipes-celery
          image: my-recipes-app:latest
          command: ['celery', '-A', 'my_recipes_web_app', 'worker', '-l', 'INFO']
          envFrom:
            - secretRef:
                name: django-app-dev-env
            - configMapRef:
                name: app-configmap
          imagePullPolicy: Never
