apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-recipes-redis
  labels:
    app: my-recipes-redis
    group: db
spec:
  selector:
    matchLabels:
      app: my-recipes-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: my-recipes-redis
        group: db
    spec:
      containers:
      - name: master
        image: redis
        ports:
        - containerPort: 6379
