# Generated by Django 4.1.3 on 2022-11-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='default-image.jpg', max_length=1000, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default-image.jpg', null=True, upload_to='thumbnails'),
        ),
    ]
