# Generated by Django 4.1.2 on 2022-11-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ranking",
            name="down",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ranking",
            name="up",
            field=models.IntegerField(default=0),
        ),
    ]
