# Generated by Django 4.1.3 on 2022-11-08 15:16

from django.db import migrations, models

import app.enums


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientquantity",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    (app.enums.UnitChoice["ml"], "milliliter"),
                    (app.enums.UnitChoice["l"], "liter"),
                    (app.enums.UnitChoice["tsp"], "teaspoon"),
                    (app.enums.UnitChoice["tbsp"], "tablespoon"),
                    (app.enums.UnitChoice["mg"], "milligram"),
                    (app.enums.UnitChoice["g"], "gram"),
                    (app.enums.UnitChoice["kg"], "kilogram"),
                    (app.enums.UnitChoice["lb"], "pound"),
                    (app.enums.UnitChoice["oz"], "ounce"),
                    (app.enums.UnitChoice["piece"], "piece"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
