# Generated by Django 4.1.3 on 2022-11-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_ingredientquantity_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientquantity",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ml", "milliliter"),
                    ("l", "liter"),
                    ("tsp", "teaspoon"),
                    ("tbsp", "tablespoon"),
                    ("mg", "milligram"),
                    ("g", "gram"),
                    ("kg", "kilogram"),
                    ("lb", "pound"),
                    ("oz", "ounce"),
                    ("piece", "piece"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="language",
            field=models.CharField(
                choices=[("EN", "English"), ("FR", "Français"), ("PL", "Polski")],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="votehistory",
            name="vote",
            field=models.CharField(
                choices=[("UP", "Up"), ("DOWN", "Down")], max_length=16
            ),
        ),
    ]
