# Generated by Django 4.1.2 on 2022-11-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ranking_down_alter_ranking_up'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='votehistory',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_vote'),
        ),
    ]
