# Generated by Django 4.1.3 on 2022-11-23 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_recipe_recipes_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='app.recipe'),
        ),
    ]
